### ISSUE TITLE
Spaceline theming

### ISSUE THREAD

**Issue by ghost** [balajisivaraman/emacs-one-themes#6]
Spaceline support is mentioned, however I can't figure out how to enable it. What am I missing?

**Comment by balajisivaraman** [comment]
@billop, Spaceline support is already available, as you can see [here](https://github.com/balajisivaraman/emacs-one-themes/blob/master/one-themes.el#L490).

If Spaceline is available and enabled, then the theme will use appropriate colours in the modeline for Spaceline.

If this is some other specific issue you're seeing, could you share a screenshot of what it is that you are seeing? Thanks.

**Comment by ghost** [comment]
I figure out that I needed to explicity load the theme, but I see that it doesn't change much. Any advice on how to replicate something like [onedark.vim](https://raw.githubusercontent.com/joshdick/onedark.vim/master/img/readme_header.png)?
